[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  SECRETS_SCAN_ENABLED = false
  SECRETS_SCAN_SMART_DETECTION_ENABLED = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api.stripe.com https://*.supabase.co;"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/**/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/**/*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/**/*.tsx"
  [headers.values]
    Content-Type = "text/x-typescript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/**/*.ts"
  [headers.values]
    Content-Type = "text/x-typescript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/src/**/*"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "*.ico"
  [headers.values]
    Content-Type = "image/x-icon"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "/images/*"
  [headers.values]
    Content-Type = "image/jpeg"
    Cache-Control = "public, max-age=31536000"